require('dotenv').config();
const express = require('express');
const { exec, execSync, spawn } = require('child_process');
const bcrypt = require('bcrypt');
const jwt = require('jsonwebtoken');
const path = require('path');
const fs = require('fs');
const WebSocket = require('ws');  // Import the WebSocket library
const recursive = require('recursive-readdir');
const sqlite3 = require('sqlite3').verbose();
const { Client } = require('ssh2');
const os = require('os');
const util = require('util');
const JSZip = require('jszip');
const fsPromises = require('fs').promises;
const { promisify } = require('util');
const { pipeline } = require('stream/promises');
const { join } = require('path');
const fileUpload = require('express-fileupload');
const unzipper = require('unzipper');
const { Worker } = require('worker_threads');
const sharp = require('sharp');
const { PDFImage } = require('pdf-image');
let wss;

const { getEasternTime, getFormattedDate, getEasternDateHour, cleanupExpiredTokens, logServerAction, logSFTPServerAction } = require('./utils');  // Adjust the path as necessary based on your file structure
const app = express();
const port = 8087;
const users = {
  admin: {
    username: "admin",
    // This is a hashed password generated by bcrypt
    password: process.env.ADMIN_PASSWORD_HASH
  }
};
const sftpConnectionDetails = {
  host: process.env.SFTP_HOST,
  port: process.env.SFTP_PORT,
  username: process.env.SFTP_USERNAME,
  password: process.env.SFTP_PASSWORD,
  readyTimeout: 600000,
  keepaliveInterval: 10000
};
const videoCacheDir = process.env.VIDEO_CACHE_DIR || path.join(os.tmpdir(), 'video_cache');

if (!fs.existsSync(videoCacheDir)) {
  fs.mkdirSync(videoCacheDir, { recursive: true });
}
const authenticateJWT = (req, res, next) => {
  const authHeader = req.headers.authorization;

  if (authHeader) {
    const token = authHeader.split(' ')[1];

    db.get('SELECT token FROM blacklisted_tokens WHERE token = ?', [token], (err, row) => {
      if (err) {
        return res.status(500).send('Error checking token');
      }
      if (row) {
        return res.status(401).send('Token has been blacklisted');
      }

      jwt.verify(token, process.env.JWT_SECRET, (err, user) => {
        if (err) {
          return res.sendStatus(403);
        }
        req.user = user;
        next();
      });
    });
  } else {
    res.sendStatus(401);
  }
};

const db = new sqlite3.Database('./token_blacklist.db', sqlite3.OPEN_READWRITE | sqlite3.OPEN_CREATE, (err) => {
  if (err) {
    console.error(err.message);
  }
  db.run('CREATE TABLE IF NOT EXISTS blacklisted_tokens(token TEXT UNIQUE)', (err) => {
    if (err) {
      console.error(err.message);
    }
  });
});

const sftpStat = promisify((sftp, path, callback) => sftp.stat(path, callback));
const sftpReadStream = (sftp, remotePath) => sftp.createReadStream(remotePath);
const normalizeSftpPath = (targetPath) => {
  if (!targetPath || targetPath.trim() === '') {
    return '/';
  }
  let normalized = path.posix.normalize(targetPath);
  if (!normalized.startsWith('/')) {
    normalized = `/${normalized}`;
  }
  return normalized;
};

async function findClosestExistingDirectory(sftp, targetPath) {
  let current = normalizeSftpPath(targetPath);

  while (true) {
    try {
      const stats = await sftpStat(sftp, current);
      if (stats && typeof stats.isDirectory === 'function') {
        if (stats.isDirectory()) {
          return current;
        }
      } else {
        return current;
      }

      if (current === '/') {
        return '/';
      }
      current = path.posix.dirname(current);
    } catch (err) {
      if (err && err.code === 2) {
        if (current === '/') {
          return '/';
        }
        current = path.posix.dirname(current);
        continue;
      }
      throw err;
    }
  }
}

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'public', 'login.html'));
});
app.use(express.static('public')); // Serve static files from 'public' directory
// Serve static files from 'assets' directory
// Middleware to parse URL-encoded bodies (as sent by HTML forms)
app.use(express.urlencoded({ extended: true, limit: '50gb' }));
app.use('/assets', express.static('assets'));
app.use(express.json({ limit: '50gb' })); // Parse JSON bodies
app.use(fileUpload({
  useTempFiles: true,
  tempFileDir: process.env.TMP_UPLOAD_SERVER_PATH,  // Adjust this to your preferred temporary directory
  limits: { fileSize: 50 * 1024 * 1024 * 1024 }  // Set the limit to 2GB
}));
app.use((err, req, res, next) => {
  if (err && err.code === 'LIMIT_FILE_SIZE') {
    return res.status(413).send('File size exceeds the 50GB limit. Please upload a smaller file.');
  }
  next(err);
});
let serverRunning = false; // Variable to track the server state
let lastBackupHour = null;
app.get('/status', (req, res) => {
  res.json({ running: serverRunning });
});
// Start the Minecraft server
app.post('/start', authenticateJWT, (req, res) => {
  const subprocess = exec(`sh ${process.env.START_COMMAND_PATH}`);

  subprocess.stdout.on('data', (data) => {
    console.log(`stdout: ${data}`);
  });

  subprocess.stderr.on('data', (data) => {
    console.error(`stderr: ${data}`);
  });

  subprocess.on('error', (error) => {
    console.error(`exec error: ${error}`);
    res.status(500).send('Failed to start the server');
  });

  // Send a response back immediately after starting the server
  serverRunning = true; // Set to true when server starts
  res.send('Server start command executed');
  console.log(`Server start command executed at ${getEasternTime()}`);
  logServerAction('Server Started');
});

// Stop the Minecraft server
app.post('/stop', authenticateJWT, (req, res) => {
  // Sends the "stop" command to the Minecraft server running in a screen session
  exec('screen -S MinecraftSession -p 0 -X stuff "stop"$(printf "\\r")', (error, stdout, stderr) => {
    if (error) {
      console.error(`exec error: ${error}`);
      return res.status(500).send('Failed to stop the server');
    }
    serverRunning = false; // Set to false when server stops
    res.send('Server stop command issued successfully');
    console.log(`Server stop command executed at ${getEasternTime()}`);
    logServerAction('Server Stopped');
  });
});
app.post('/restart', authenticateJWT, (req, res) => {
  if (!serverRunning) {
    res.status(400).send('Server is not currently running.');
    return;
  }
  // Sends the "stop" command to the Minecraft server running in a screen session
  exec('screen -S MinecraftSession -p 0 -X stuff "stop$(printf "\\r")"', (error, stdout, stderr) => {
    if (error) {
      console.error(`exec error: ${error}`);
      res.status(500).send('Failed to stop the server');
      return;
    }

    console.log(`Server stop command executed at ${getEasternTime()}`);
    serverRunning = false; // Update the server running status

    // Wait for 3 seconds before starting the server again
    setTimeout(() => {
      startServer();
      res.send('Server is being restarted'); // Inform the client that the restart process has been initiated
      logServerAction('Server Restarted');
    }, 3000);
  });
});
app.post('/login', async (req, res) => {
  const { username, password } = req.body;

  // Check if the user exists
  const user = users[username];
  if (user) {
    // Compare hashed password
    const match = await bcrypt.compare(password, user.password);
    if (match) {
      // Create and assign a token
      const token = jwt.sign({ username: user.username }, process.env.JWT_SECRET, { expiresIn: '1h' });
      res.json({ message: "Authentication successful!", token });
      logServerAction('Logged In');
    } else {
      res.status(401).send("Invalid Credentials");
    }
  } else {
    res.status(401).send("User does not exist");
  }
});
app.post('/logout', authenticateJWT, (req, res) => {
  const token = req.headers.authorization.split(' ')[1];
  db.run('INSERT INTO blacklisted_tokens(token) VALUES(?)', [token], function (err) {
    if (err) {
      res.status(500).send("Failed to blacklist token");
      return console.error(err.message);
    }
    console.log('Logged out');
    logServerAction('Logged Out');
    cleanupExpiredTokens();
    res.send("Logged out");
  });
});
// Backup Minecraft server
app.post('/backup', authenticateJWT, async (req, res) => {
  const now = new Date();
  const currentHour = getEasternDateHour();

  if (lastBackupHour === currentHour) {
    return res.status(429).send('A backup has already been performed this hour.');
  }

  let wasServerRunning = serverRunning; // Store the state of the server
  if (serverRunning) {
    execSync('screen -S MinecraftSession -p 0 -X stuff "stop$(printf "\\r")"');
    serverRunning = false;
    console.log(`Server stopped for backup at ${getEasternTime()}`);
    logServerAction('Server Stopped for Backup');
    setTimeout(() => performBackup(currentHour, now, wasServerRunning, res), 3000)
  }
  else {
    setTimeout(() => performBackup(currentHour, now, wasServerRunning, res), 5)
  }
});
// Utility function to calculate directory size
function calculateDirectorySize(directoryPath) {
  return new Promise((resolve, reject) => {
    // Define an array of patterns or filenames to ignore
    const ignoreFiles = [
      '.zsh_sessions',
      '.bash_history',
      '.zsh_history',
      // Include patterns to ignore any hidden files or specific directories if necessary
      '.*', // Ignores all hidden files (files starting with a dot)
      '**/node_modules/**' // Ignores all node_modules directories
    ];

    recursive(directoryPath, ignoreFiles, (err, files) => {
      if (err) {
        reject(err);
      } else {
        let totalSize = 0;
        files.forEach(file => {
          try {
            totalSize += fs.statSync(file).size;
          } catch (err) {
            console.error(`Error accessing file ${file}: ${err}`);
            // Optionally handle errors, e.g., permission issues or file not found, without throwing
          }
        });
        resolve(totalSize);
      }
    });
  });
}
// Function to handle the backup process
function performBackup(currentHour, now, wasServerRunning, res) {
  try {
    const dateFolder = getFormattedDate(now);
    const hourLabel = now.getHours() >= 12 ? `${(now.getHours() % 12) || 12} PM` : `${now.getHours()} AM`;
    const backupPath = `${process.env.BACKUP_PATH}/${dateFolder}/${hourLabel}`;
    fs.mkdirSync(backupPath, { recursive: true });

    // Call calculateDirectorySize and wait for the result before starting rsync
    calculateDirectorySize(process.env.MINECRAFT_SERVER_PATH)
      .then(totalSize => {
        let totalTransferred = 0; // Initialize the total transferred bytes

        const rsync = spawn('rsync', [
          '-avh',
          '--info=progress2',
          '--out-format=%n %l %b', // Custom format: filename, total size, bytes transferred
          '--exclude', '.zsh_sessions',
          '--exclude', '.bash_history',
          '--exclude', '.zsh_history',
          `${process.env.MINECRAFT_SERVER_PATH}`,
          `${backupPath}`
        ]);


        rsync.stdout.on('data', (data) => {
          const progressData = data.toString();
          console.log(progressData); // Log the raw data for debugging

          // Match the custom output format for transferred bytes
          const match = progressData.match(/[\w\.\-]+ (\d+) (\d+)/);

          if (match) {
            const fileSize = parseInt(match[1], 10);
            const transferredBytes = parseInt(match[2], 10);

            totalTransferred += transferredBytes;

            // Calculate the overall progress
            const progress = Math.min(Math.round((totalTransferred / totalSize) * 100), 100);
            console.log(`Broadcasting progress: ${progress}%`);
            broadcastBackupProgress({ type: 'progress', value: progress });
          }
        });

        rsync.stderr.on('data', (data) => {
          console.error(`rsync stderr: ${data.toString()}`);
        });

        rsync.on('close', (code) => {
          if (code === 0) {
            console.log(`Backup performed successfully at ${getEasternTime()}`);
            logServerAction('Server Backed Up');
            res.send('Backup performed successfully');
            lastBackupHour = currentHour;
            if (wasServerRunning) {
              startServer();
            }
          } else {
            console.error(`Backup failed with exit code: ${code}`);
            res.status(500).send('Failed to perform backup');
          }
        });

      }).catch(err => {
        console.error(`Error calculating directory size: ${err}`);
        res.status(500).send('Failed to calculate directory size for backup');
      });

  } catch (error) {
    console.error(`Backup failed: ${error}`);
    res.status(500).send('Failed to perform backup');
  }
}
// Additional function to start the server if it was running before
function startServer() {
  exec(`sh ${process.env.START_COMMAND_PATH}`, (error) => {
    if (error) {
      console.error(`Error starting the server: ${error}`);
    } else {
      serverRunning = true;
      console.log(`Server restarted after backup at ${getEasternTime()}`);
      logServerAction('Server Started');
    }
  });
}
// Broadcasts progress data to all connected WebSocket clients
function broadcastBackupProgress(message) {
  const data = JSON.stringify(message);
  wss.clients.forEach(function each(client) {
    if (client.readyState === WebSocket.OPEN) {
      client.send(data);
    }
  });
}
// Endpoint to list files in a directory
app.get('/sftp/list', authenticateJWT, (req, res) => {
  const dirPath = normalizeSftpPath(req.query.path || '/'); // Default path is the root directory

  const conn = new Client();
  conn.on('ready', () => {
      conn.sftp((err, sftp) => {
          if (err) {
              console.error('SFTP session error:', err);
              res.status(500).send('Failed to start SFTP session');
              conn.end();
              return;
          }

          sftp.readdir(dirPath, async (err, list) => {
              if (err) {
                  const isMissingDirectory = err && (err.code === 2 || (err.message && err.message.toLowerCase().includes('no such file')));
                  if (isMissingDirectory) {
                    try {
                      const fallbackPath = await findClosestExistingDirectory(sftp, dirPath);
                      res.status(404).json({
                        message: 'Directory no longer exists',
                        deletedPath: dirPath,
                        fallbackPath
                      });
                    } catch (fallbackError) {
                      console.error('Directory recovery error:', fallbackError);
                      res.status(500).send('Failed to recover directory');
                    }
                  } else {
                    console.error('Directory read error:', err);
                    res.status(500).send('Failed to read directory');
                  }
                  conn.end();
                  return;
              }
              const filteredList = list.filter(item => !item.filename.startsWith('.'));
              // Sort the list by modification time (mtime)
              filteredList.sort((a, b) => b.attrs.mtime - a.attrs.mtime);
              res.json(filteredList.map(item => ({
                  name: item.filename,
                  type: item.longname[0] === 'd' ? 'directory' : 'file',
                  size: item.attrs.size,
                  modified: item.attrs.mtime * 1000 // Convert to milliseconds
              })));
              conn.end();
          });
      });
  }).on('error', (err) => {
      console.error('Connection error:', err);
      res.status(500).send('Failed to connect to SFTP server');
  }).connect(sftpConnectionDetails);
});

let currentPath = '/'; // default path

app.post('/change-directory', authenticateJWT, (req, res) => {
  const newPath = req.body.path;
  // You may want to add some validation here to ensure the path is safe to use
  currentPath = newPath;
  res.json({ path: currentPath });
});

app.post('/open-directory', authenticateJWT, (req, res) => {
  const newPath = req.body.path;
  if (!newPath.startsWith('/')) {
    // Ensuring the path is absolute and normalized, preventing directory traversal attacks
    currentPath = path.join(currentPath, newPath);
  } else {
    currentPath = newPath;
  }
  res.json({ path: currentPath });
});

const downloads = {};
const tempDownloadLinks = new Map();

app.post('/download', (req, res) => {
  const { token, path: filePath, requestId: frontendRequestId } = req.body;
  const formattedIpAddress = req.headers['x-forwarded-for'] || req.connection.remoteAddress;

  jwt.verify(token, process.env.JWT_SECRET, (err, user) => {
    if (err) {
      logSFTPServerAction('unknown', 'download', filePath, formattedIpAddress);
      return res.sendStatus(403);
    }

    const requestId = frontendRequestId || generateUniqueId();

    if (!downloads[requestId]) {
      const worker = new Worker(path.join(__dirname, 'downloadWorker.js'), {
        workerData: {
          filePath,
          user,
          requestId,
          formattedIpAddress
        }
      });

      downloads[requestId] = { worker, status: 'in-progress', filePath: null };

      worker.on('message', message => {
        if (message.type === 'progress') {
          broadcastDownloadProgress(requestId, message.progress);
        } else if (message.type === 'done') {
          downloads[requestId].status = 'ready';
          downloads[requestId].filePath = message.filePath;
          tempDownloadLinks.set(requestId, message.filePath);
          broadcastDownloadProgress(requestId, 100);

          wss.clients.forEach(client => {
            if (client.readyState === WebSocket.OPEN) {
              client.send(JSON.stringify({ type: 'complete', requestId }));
            }
          });
        }
      });

      worker.on('error', err => {
        console.error(`[Worker ${requestId}] error:`, err);
        downloads[requestId].status = 'error';
      });

      worker.on('exit', code => {
        if (code !== 0) {
          console.error(`[Worker ${requestId}] exited with code ${code}`);
        }
      });
    }

    res.json({ requestId, message: 'Download queued' });
  });
});

app.get('/downloads/:requestId', (req, res) => {
  const requestId = req.params.requestId;
  const filePath = tempDownloadLinks.get(requestId);

  if (!filePath || !fs.existsSync(filePath)) {
    return res.status(404).send('File not found');
  }

  const filename = path.basename(filePath);
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.setHeader('Content-Type', 'application/zip');
  res.setHeader('Content-Length', fs.statSync(filePath).size);

  const stream = fs.createReadStream(filePath);
  stream.pipe(res);

  res.on('finish', () => {
    fs.unlink(filePath, () => {});
    tempDownloadLinks.delete(requestId);
  });
});

function broadcastDownloadProgress(requestId, progress) {
  if (!requestId) {
    return;
  }

  if (!wss || !wss.clients) {
    return;
  }

  wss.clients.forEach(client => {
    if (client.readyState === WebSocket.OPEN) {
      client.send(JSON.stringify({ type: 'progress', requestId, progress }));
    }
  });
}

function generateUniqueId() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
    const r = Math.random() * 16 | 0,
      v = c === 'x' ? r : (c === 'y' ? (r & 0x3 | 0x8) : r);
    return v.toString(16);
  });
}

app.post('/upload', authenticateJWT, (req, res) => {
  let files = req.files.files; // Files uploaded
  const destinationPath = req.body.path; // Destination directory
  const lastModifiedRaw = req.body.lastModified;
  const parsedLastModified = Array.isArray(lastModifiedRaw)
    ? parseInt(lastModifiedRaw[0], 10)
    : parseInt(lastModifiedRaw, 10);
  const lastModified = Number.isFinite(parsedLastModified) ? parsedLastModified : Date.now();

  console.log('Files received:', files);
  console.log('Destination path:', destinationPath);

  const conn = new Client();
  conn.on('ready', () => {
      conn.sftp(async (err, sftp) => {
          if (err) {
              console.error('SFTP connection error:', err);
              res.status(500).send('SFTP connection error: ' + err.message);
              return;
          }

          try {
              if (!Array.isArray(files)) {
                  files = [files];
              }

              for (const file of files) {
                  let localFilePath = file.tempFilePath || file.path;
                  console.log('Processing file:', file.name);
                  console.log('Local file path:', localFilePath);

                  if (!localFilePath) {
                      throw new Error('Local file path is undefined for file: ' + file.name);
                  }

                  let relativeFilePath = file.name;
                  let remoteFilePath = path.join(destinationPath, relativeFilePath);

                  // Ensure the remote directory exists
                  const remoteDir = path.dirname(remoteFilePath);
                  await ensureDirectoryExists(sftp, remoteDir);

                  // Check if the file exists and modify the file name if necessary
                  remoteFilePath = await getUniqueFilePath(sftp, remoteFilePath);

                  console.log(`Uploading ${localFilePath} to ${remoteFilePath}`);

                  // Upload the file
                  await new Promise((resolve, reject) => {
                      sftp.fastPut(localFilePath, remoteFilePath, (err) => {
                          if (err) reject(err);
                          else resolve();
                      });
                  });

                  const modifiedDate = new Date(lastModified);
                  await new Promise((resolve, reject) => {
                      sftp.utimes(remoteFilePath, modifiedDate, modifiedDate, (err) => {
                          if (err) reject(err);
                          else resolve();
                      });
                  });

                  // If the file is a ZIP file, unzip it into a new directory
                  if (path.extname(file.name) === '.zip') {
                      let baseName = path.basename(file.name, '.zip');
                      const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), `${baseName}-`));
                      let newDir = path.join(destinationPath, baseName);
                      const expectedZipSize = Number(file.size);

                      // Ensure the directory does not overwrite an existing one
                      newDir = await getUniqueDirectoryPath(sftp, newDir);

                      if (Number.isFinite(expectedZipSize)) {
                        const stats = fs.statSync(localFilePath);
                        if (stats.size !== expectedZipSize) {
                          throw new Error(`ZIP size mismatch: expected ${expectedZipSize}, got ${stats.size}`);
                        }
                      }
                      await unzipFile(localFilePath, tempDir);
                      await ensureDirectoryExists(sftp, newDir);
                      await uploadDirectory(sftp, tempDir, newDir);
                      fs.rmSync(tempDir, { recursive: true, force: true });
                      // Remove the ZIP file after extraction and upload
                      await new Promise((resolve, reject) => {
                          sftp.unlink(remoteFilePath, (err) => {
                              if (err) reject(err);
                              else resolve();
                          });
                      });
                      console.log(`Deleted ZIP file: ${remoteFilePath}`);
                  }

                  // Clean up the temporary file after all operations are completed
                  fs.unlink(localFilePath, (err) => {
                      if (err) console.error('Error deleting temp file:', err);
                      else console.log('Temp file deleted:', localFilePath);
                  });

                  // Log the upload activity
                  const ipAddress = req.headers['x-forwarded-for'] || req.connection.remoteAddress;
                  console.log('IP Address:', ipAddress); // Debug logging
                  logSFTPServerAction(req.user.username, 'upload', remoteFilePath, ipAddress);
              }

              res.send('Files uploaded successfully');
          } catch (error) {
              console.error('Error uploading files:', error);
              res.status(500).send('Error uploading files: ' + error.message);
          } finally {
              conn.end();
          }
      });
  }).connect(sftpConnectionDetails);
});


async function getUniqueFilePath(sftp, remoteFilePath) {
  let baseName = path.basename(remoteFilePath, path.extname(remoteFilePath));
  let ext = path.extname(remoteFilePath);
  let dir = path.dirname(remoteFilePath);
  let uniqueFilePath = remoteFilePath;
  let counter = 1;

  // Check if file exists and modify name if necessary
  while (await fileExists(sftp, uniqueFilePath)) {
    uniqueFilePath = path.join(dir, `${baseName} copy${counter}${ext}`);
    counter++;
  }

  return uniqueFilePath;
}
async function getUniqueDirectoryPath(sftp, remoteDirPath) {
  let uniqueDirPath = remoteDirPath;
  let counter = 2;

  // Check if directory exists and modify the name if necessary
  while (await fileExists(sftp, uniqueDirPath)) {
      uniqueDirPath = path.join(path.dirname(remoteDirPath), `${path.basename(remoteDirPath)}-${counter}`);
      counter++;
  }

  return uniqueDirPath;
}

async function fileExists(sftp, remoteFilePath) {
  return new Promise((resolve, reject) => {
      sftp.stat(remoteFilePath, (err, stats) => {
          if (err) {
              if (err.code === 2) {
                  // File or directory does not exist
                  resolve(false);
              } else {
                  // Some other error
                  reject(err);
              }
          } else {
              // File or directory exists
              resolve(true);
          }
      });
  });
}

async function unzipFile(zipFilePath, destinationPath) {
  return new Promise((resolve, reject) => {
    const unzip = spawn('unzip', ['-o', '-qq', zipFilePath, '-d', destinationPath], {
      stdio: ['ignore', 'ignore', 'pipe']
    });
    let stderr = '';
    const timeoutId = setTimeout(() => {
      unzip.kill('SIGKILL');
      reject(new Error('unzip timed out'));
    }, 10 * 60 * 1000);

    unzip.stderr.on('data', (data) => {
      stderr += data.toString();
    });

    unzip.on('close', (code) => {
      clearTimeout(timeoutId);
      if (code !== 0) {
        reject(new Error(`unzip failed with code ${code}${stderr ? `: ${stderr.trim()}` : ''}`));
        return;
      }
      console.log(`Unzipped file to ${destinationPath}`);
      resolve();
    });

    unzip.on('error', (err) => {
      clearTimeout(timeoutId);
      reject(err);
    });
  });
}

async function uploadDirectory(sftp, localDir, remoteDir) {
  const items = fs.readdirSync(localDir);
  for (const item of items) {
    const localItemPath = path.join(localDir, item);
    const remoteItemPath = path.join(remoteDir, item);

    let stats;
    try {
      stats = fs.lstatSync(localItemPath);
    } catch (error) {
      if (error && error.code === 'ENOENT') {
        console.warn(`Skipping missing item during upload: ${localItemPath}`);
        continue;
      }
      throw error;
    }

    if (stats.isSymbolicLink()) {
      console.warn(`Skipping symlink during upload: ${localItemPath}`);
      continue;
    }

    if (stats.isDirectory()) {
      await ensureDirectoryExists(sftp, remoteItemPath);
      await uploadDirectory(sftp, localItemPath, remoteItemPath);
    } else {
      await new Promise((resolve, reject) => {
        sftp.fastPut(localItemPath, remoteItemPath, (err) => {
          if (err) reject(err);
          else resolve();
        });
      });
    }
  }
}

async function ensureDirectoryExists(sftp, dir) {
  const dirs = dir.split('/');
  let currentDir = '';

  for (const part of dirs) {
    if (part) {
      currentDir += '/' + part;

      try {
        await new Promise((resolve, reject) => {
          sftp.stat(currentDir, (err, stats) => {
            if (err) {
              if (err.code === 2) {
                // Directory does not exist, create it
                sftp.mkdir(currentDir, (err) => {
                  if (err) reject(err);
                  else resolve();
                });
              } else {
                reject(err);
              }
            } else {
              // Directory exists, continue
              resolve();
            }
          });
        });
      } catch (error) {
        if (error.code !== 4) {
          // Ignore "Failure" code if directory already exists
          throw error;
        }
      }
    }
  }
}



const cacheDir = path.join(os.tmpdir(), 'image_cache');

if (!fs.existsSync(cacheDir)) {
  fs.mkdirSync(cacheDir);
}

app.get('/download-preview', authenticateJWT, (req, res) => {
  const filePath = req.query.path;

  const conn = new Client();
  conn.on('ready', () => {
    conn.sftp((err, sftp) => {
      if (err) {
        console.error('SFTP connection error:', err);
        res.status(500).send('SFTP connection error');
        return;
      }

      const fileExtension = path.extname(filePath).toLowerCase();
      const cacheFilePath = path.join(cacheDir, path.basename(filePath) + '.jpg');

      if (fileExtension === '.pdf') {
        handlePDF(sftp, filePath, cacheFilePath, res);
      } else if (fileExtension === '.heic') {
        handleHEIC(sftp, filePath, cacheFilePath, res);
      } else if (/\.(mp4|mov|avi|webm|mkv)$/i.test(filePath)) {
        handleVideo(sftp, filePath, cacheFilePath, res);
      } else if (/\.(jpg|jpeg|png|gif|bmp|webp)$/i.test(filePath)) {
        handleImage(sftp, filePath, cacheFilePath, res);
      } else {
        streamFile(sftp, filePath, res);
      }
    });
  }).connect(sftpConnectionDetails);
});

function handleVideo(sftp, filePath, cacheFilePath, res) {
  const videoCacheFilePath = path.join(videoCacheDir, path.basename(filePath) + '.jpg');

  if (fs.existsSync(videoCacheFilePath)) {
    return res.sendFile(videoCacheFilePath);
  }

  const tempLocalVideoPath = path.join(os.tmpdir(), `${path.basename(filePath)}`);
  const tempThumbnailPath = path.join(os.tmpdir(), `${path.basename(filePath)}.jpg`);
  const videoStream = sftp.createReadStream(filePath);
  const videoFileWriteStream = fs.createWriteStream(tempLocalVideoPath);

  videoStream.pipe(videoFileWriteStream);

  videoFileWriteStream.on('finish', () => {
    const runFfmpeg = (timestamp) => new Promise((resolve, reject) => {
      const ffmpeg = spawn('ffmpeg', [
        '-i', tempLocalVideoPath,
        '-ss', timestamp,
        '-vframes', '1',
        '-q:v', '5',
        '-vf', 'eq=brightness=0.05:saturation=1.2',
        tempThumbnailPath
      ]);

      let stderr = '';
      ffmpeg.stderr.on('data', (data) => {
        stderr += data.toString();
      });

      ffmpeg.on('close', (code) => {
        if (code !== 0) {
          return reject(new Error(`ffmpeg exited with code ${code}${stderr ? `: ${stderr.trim()}` : ''}`));
        }
        resolve();
      });

      ffmpeg.on('error', (error) => {
        reject(error);
      });
    });

    runFfmpeg('00:00:01')
      .catch((error) => {
        console.warn(`ffmpeg failed at 00:00:01, retrying at 00:00:00: ${error.message}`);
        return runFfmpeg('00:00:00');
      })
      .then(() => {
        fs.copyFileSync(tempThumbnailPath, videoCacheFilePath);
        res.setHeader('Content-Type', 'image/jpeg');
        res.sendFile(videoCacheFilePath, (err) => cleanupFiles(tempLocalVideoPath, tempThumbnailPath, err, res));
      })
      .catch((error) => {
        console.error('Error generating video thumbnail:', error.message);
        res.status(500).send('Error generating video thumbnail');
      });
  });

  videoFileWriteStream.on('error', (err) => {
    console.error('Error writing video file:', err);
    res.status(500).send('Error downloading video for thumbnail generation');
  });
}

const MAX_WORKERS = Math.max(1, os.cpus().filter(cpu => cpu.speed > 2000).length);
const workerPool = [];
const taskQueue = [];
let activeWorkers = 0;

for (let i = 0; i < MAX_WORKERS; i++) {
  const worker = new Worker(path.join(__dirname, 'heicWorker.js'));
  workerPool.push(worker);
}

function assignTaskToWorker(task) {
  if (workerPool.length > 0) {
    const worker = workerPool.pop();
    activeWorkers++;

    worker.postMessage(task.data);

    worker.once('message', (message) => {
      task.resolve(message);
      workerPool.push(worker);
      activeWorkers--;
      processQueue();
    });

    worker.once('error', (error) => {
      task.reject(error);
      workerPool.push(worker);
      activeWorkers--;
      processQueue();
    });

    worker.once('exit', (code) => {
      if (code !== 0) {
        console.error(`Worker exited with code ${code}`);
        task.reject(new Error(`Worker exited with code ${code}`));
      }
      workerPool.push(worker);
      activeWorkers--;
      processQueue();
    });
  } else {
    taskQueue.push(task);
  }
}

function scheduleTask(data) {
  return new Promise((resolve, reject) => {
    assignTaskToWorker({ data, resolve, reject });
  });
}

function handleHEIC(sftp, filePath, cacheFilePath, res) {
  const placeholderImagePath = path.join(__dirname, 'assets', 'android-chrome-512x512.png');

  if (fs.existsSync(cacheFilePath)) {
    return res.sendFile(cacheFilePath);
  }

  const chunks = [];
  const readStream = sftp.createReadStream(filePath);

  readStream.on('data', (chunk) => chunks.push(chunk));
  readStream.on('end', () => {
    const heicBuffer = Buffer.concat(chunks);

    scheduleTask({ heicBuffer, cacheFilePath })
      .then((message) => {
        if (message.success) {
          res.setHeader('Content-Type', 'image/jpeg');
          res.sendFile(message.cacheFilePath);
        } else {
          console.error('Error generating HEIC thumbnail:', message.error);
          res.sendFile(placeholderImagePath);
        }
      })
      .catch((error) => {
        console.error('Error processing HEIC file:', error);
        res.sendFile(placeholderImagePath);
      });
  });

  readStream.on('error', (err) => {
    console.error('Error reading HEIC file:', err.message);
    res.sendFile(placeholderImagePath);
  });
}

function processQueue() {
  if (taskQueue.length > 0 && activeWorkers < MAX_WORKERS) {
    const task = taskQueue.shift();
    assignTaskToWorker(task);
  }
}

function handleImage(sftp, filePath, cacheFilePath, res) {
  if (fs.existsSync(cacheFilePath)) {
    return res.sendFile(cacheFilePath);
  }

  const chunks = [];
  const readStream = sftp.createReadStream(filePath);
  readStream.on('data', (chunk) => chunks.push(chunk));
  readStream.on('end', async () => {
    const imageBuffer = Buffer.concat(chunks);
    try {
      sharp(imageBuffer)
        .rotate()
        .resize(800, 600)
        .toBuffer((err, resizedBuffer) => {
          if (err) {
            console.error('Error resizing image:', err);
            return res.status(500).send('Error resizing image');
          }
          fs.writeFileSync(cacheFilePath, resizedBuffer);
          res.setHeader('Content-Type', 'image/jpeg');
          res.send(resizedBuffer);
        });
    } catch (error) {
      console.error('Error processing image:', error);
      res.status(500).send('Error processing image');
    }
  });
  readStream.on('error', (err) => {
    console.error('Error in file stream:', err);
    res.status(500).send('Error streaming image');
  });
}

function streamFile(sftp, filePath, res) {
  const readStream = sftp.createReadStream(filePath);
  res.setHeader('Content-Type', 'application/octet-stream');
  readStream.pipe(res);

  readStream.on('error', (err) => {
    console.error('Error in file stream:', err);
    res.status(500).send('Error streaming file');
  });
}

function cleanupFiles(tempLocalVideoPath, tempThumbnailPath, err, res) {
  if (err) {
    console.error('Error sending thumbnail:', err);
    return res.status(500).send('Error sending thumbnail');
  }

  fs.unlink(tempLocalVideoPath, (err) => {
    if (err) console.error('Error deleting temp video file:', err);
  });
  fs.unlink(tempThumbnailPath, (err) => {
    if (err) console.error('Error deleting temp thumbnail file:', err);
  });
}

function handlePDF(sftp, filePath, cacheFilePath, res) {
  if (fs.existsSync(cacheFilePath)) {
    return res.sendFile(cacheFilePath);
  }

  const tempPDFPath = path.join(os.tmpdir(), `${path.basename(filePath)}`);
  const pdfStream = sftp.createReadStream(filePath);
  const pdfFileWriteStream = fs.createWriteStream(tempPDFPath);

  pdfStream.pipe(pdfFileWriteStream);

  pdfFileWriteStream.on('finish', () => {
    const pdfImage = new PDFImage(tempPDFPath, { combinedImage: false });

    pdfImage.convertPage(0)
      .then((imagePath) => {
        fs.renameSync(imagePath, cacheFilePath);
        res.setHeader('Content-Type', 'image/jpeg');
        res.sendFile(cacheFilePath);
      })
      .catch(err => {
        console.error('Error converting PDF to thumbnail:', err);
        res.status(500).send('Error generating PDF thumbnail');
      })
      .finally(() => {
        fs.unlink(tempPDFPath, (err) => {
          if (err) console.error('Error deleting temp PDF file:', err);
        });
      });
  });

  pdfFileWriteStream.on('error', (err) => {
    console.error('Error writing PDF file to temp path:', err);
    res.status(500).send('Error processing PDF');
  });
}

async function precacheVideoThumbnails() {
  const conn = new Client();
  conn.on('ready', () => {
    conn.sftp(async (err, sftp) => {
      if (err) {
        console.error('SFTP session error:', err);
        return;
      }

      try {
        const startDir = '/';
        await processDirectory(sftp, startDir);
        conn.end();
      } catch (error) {
        console.error('Error during video pre-caching:', error);
      }
    });
  }).connect(sftpConnectionDetails);
}

async function processDirectory(sftp, dirPath) {
  const files = await new Promise((resolve, reject) => {
    sftp.readdir(dirPath, (err, list) => {
      if (err) reject(err);
      else resolve(list);
    });
  });

  for (const file of files) {
    const fullPath = path.join(dirPath, file.filename);
    if (file.longname.startsWith('d')) {
      await processDirectory(sftp, fullPath);
    } else if (/\.(mp4|mov|avi|webm|mkv)$/i.test(file.filename)) {
      await generateThumbnailForVideo(sftp, fullPath);
    }
  }
}

async function generateThumbnailForVideo(sftp, filePath) {
  const cacheFilePath = path.join(videoCacheDir, path.basename(filePath) + '.jpg');
  const placeholderImagePath = path.join(__dirname, 'assets', 'android-chrome-512x512.png');

  if (fs.existsSync(cacheFilePath)) {
    return;
  }

  const tempLocalVideoPath = path.join(os.tmpdir(), `${path.basename(filePath)}`);
  const tempThumbnailPath = path.join(os.tmpdir(), `${path.basename(filePath)}.jpg`);

  const videoStream = sftp.createReadStream(filePath);
  const videoFileWriteStream = fs.createWriteStream(tempLocalVideoPath);

  videoStream.pipe(videoFileWriteStream);

  return new Promise((resolve, reject) => {
    videoFileWriteStream.on('finish', () => {
      if (!fs.existsSync(tempLocalVideoPath)) {
        fs.copyFileSync(placeholderImagePath, cacheFilePath);
        return resolve();
      }

      const ffmpeg = spawn('ffmpeg', [
        '-i', tempLocalVideoPath,
        '-ss', '00:01:00',
        '-vframes', '1',
        '-q:v', '5',
        '-vf', 'eq=brightness=0.05:saturation=1.2',
        tempThumbnailPath
      ]);

      ffmpeg.on('close', (code) => {
        if (code !== 0) {
          fs.copyFileSync(placeholderImagePath, cacheFilePath);
          return resolve();
        }

        fs.copyFileSync(tempThumbnailPath, cacheFilePath);
        resolve();
      });

      ffmpeg.on('error', () => {
        fs.copyFileSync(placeholderImagePath, cacheFilePath);
        resolve();
      });
    });

    videoFileWriteStream.on('error', () => {
      fs.copyFileSync(placeholderImagePath, cacheFilePath);
      resolve();
    });
  }).finally(() => {
    if (fs.existsSync(tempLocalVideoPath)) {
      fs.unlink(tempLocalVideoPath, (err) => {
        if (err) console.error('Error deleting temp video file:', err);
      });
    }

    if (fs.existsSync(tempThumbnailPath)) {
      fs.unlink(tempThumbnailPath, (err) => {
        if (err) console.error('Error deleting temp thumbnail file:', err);
      });
    }
  });
}

app.post('/sftp/create-directory', authenticateJWT, (req, res) => {
  const { path: basePath, directoryName } = req.body;

  if (!directoryName || !basePath) {
    return res.status(400).json({ message: 'Invalid directory name or path' });
  }

  const newDirectoryPath = basePath.endsWith('/') ? basePath + directoryName : basePath + '/' + directoryName;

  const conn = new Client();
  conn.on('ready', () => {
    conn.sftp((err, sftp) => {
      if (err) {
        console.error('SFTP session error:', err);
        res.status(500).json({ message: 'Failed to start SFTP session' });
        return;
      }

      sftp.stat(newDirectoryPath, (err, stats) => {
        if (err && err.code === 2) {
          sftp.mkdir(newDirectoryPath, (err) => {
            if (err) {
              console.error('Error creating directory:', err);
              res.status(500).json({ message: 'Failed to create directory' });
            } else {
              res.json({ message: 'Directory created successfully', path: newDirectoryPath });
            }
            conn.end();
          });
        } else if (stats) {
          res.status(400).json({ message: 'A directory with that name already exists' });
          conn.end();
        } else {
          console.error('Error checking directory existence:', err);
          res.status(500).json({ message: 'Failed to check directory existence' });
          conn.end();
        }
      });
    });
  }).on('error', (err) => {
    console.error('Connection error:', err);
    res.status(500).json({ message: 'Failed to connect to SFTP server' });
  }).connect(sftpConnectionDetails);
});

const server = app.listen(port, () => {
  console.log(`Server listening at http://localhost:${port}`);
  server.timeout = 0;
  // Attach WebSocket server to the same HTTP server
  wss = new WebSocket.Server({ server });

  wss.on('connection', function connection(ws) {
    console.log('Client connected to WebSocket.');

    // Add any message handlers or other WebSocket-related code here
  });

  console.log('Starting video thumbnail pre-caching...');
  precacheVideoThumbnails();
});
